name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

        - name: checkout repo
          uses: actions/checkout@v4
          
        # Dummy Step
        - name: readme section
          run: |
            echo "My welcome message"
            ls -lrta
            cat README.md
            
        # Step 2: Set up Python environment
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.8'

        # Step 3: Install dependencies from requirements.txt
        - name: Install dependencies
          run: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt