name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

        - name: checkout repo
          uses: actions/checkout@v4
          
        - name: readme section
          run: |
            echo "My welcome message"
            ls -lrta
            cat README.md