name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:

        - name: checkout repo
          uses: actions/checkout@v4
          
        - name: readme section
          run: |
            echo "My welcome message"
            ls -lrta
            cat README.md
            
        # Step 2: Set up Python environment
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.8'